--   OEPaNIYq

INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(16, 'Валенсия', 'LA');

INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(20, 'Эспаньол', 'LA');

INSERT INTO PUBLIC.FOOTBALL_BOOKIE_STATS
(ID, DRAW_RATE, GUEST_RATE, HOME_RATE)
VALUES(53, 4.5, 1.64, 4.59);


INSERT INTO PUBLIC.FOOTBALL_REFEREE
(ID, NAME)
VALUES(19, 'Villanueva I. (Исп)');


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(151, 0, 0, 'FIRST', 0, 'DRAW', 6, 4, 7, 6, 3, 77, 2, 5, 3, 0, 3, 23);

INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(153, 1, 1, 'SECOND', 2, 'DRAW', 3, 7, 5, 2, 5, 61, 1, 7, 5, 1, 0, 39);

INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(152, 1, 1, 'MATCH', 2, 'DRAW', 9, 11, 12, 8, 8, 69, 3, 12, 8, 1, 3, 31);


INSERT INTO PUBLIC.FOOTBALL_MATCH_INFO
(ID, FIRST_PERIOD_ID, MATCH_ID, SECOND_PERIOD_ID)
VALUES(53, 151, 152, 153);


INSERT INTO PUBLIC.FOOTBALL_MATCH
(ID, CHAMPIONSHIP, "DATE", MYSCORE_CODE, SEASON, BOOKIE_STATS_ID, GUEST_TEAM_ID, HOME_TEAM_ID, MATCH_INFO_ID, REFEREE_ID)
VALUES(53, 'LA', '2017-11-26 22:45:00.000', 'OEPaNIYq', 'S2017', 53, 20, 16, 53, 19);


INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (283, 32, 'YELLOW', 'HOME', 16);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (284, 44, 'YELLOW', 'HOME', 16);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (285, 74, 'YELLOW', 'HOME', 16);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (286, 89, 'YELLOW', 'HOME', 16);

INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (151, 283);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (151, 284);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (153, 285);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (153, 286);




