--   vT8fEudT

INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(10, 'Леганес', 'LA');


INSERT INTO PUBLIC.FOOTBALL_BOOKIE_STATS
(ID, DRAW_RATE, GUEST_RATE, HOME_RATE)
VALUES(69, 5, 1.36, 9);

INSERT INTO PUBLIC.FOOTBALL_REFEREE
(ID, NAME)
VALUES(13, 'Мальенко А. (Исп)');



INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(199, 1, 0, 'FIRST', 1, 'GUEST', 2, 5, 3, 1, 2, 68, 3, 8, 6, 1, 0, 32);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(201, 2, 0, 'SECOND', 2, 'GUEST', 1, 5, 8, 6, 3, 68, 3, 17, 12, 6, 0, 32);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(200, 3, 0, 'MATCH', 3, 'GUEST', 3, 10, 11, 7, 5, 68, 6, 25, 18, 7, 0, 32);


INSERT INTO PUBLIC.FOOTBALL_MATCH_INFO
(ID, FIRST_PERIOD_ID, MATCH_ID, SECOND_PERIOD_ID)
VALUES(69, 199, 200, 201);


INSERT INTO PUBLIC.FOOTBALL_MATCH
(ID, CHAMPIONSHIP, "DATE", MYSCORE_CODE, SEASON, BOOKIE_STATS_ID, GUEST_TEAM_ID, HOME_TEAM_ID, MATCH_INFO_ID, REFEREE_ID)
VALUES(69, 'LA', '2017-11-18 18:15:00.000', 'vT8fEudT', 'S2017', 69, 20, 10, 69, 13);


INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (370, 29, 'YELLOW', 'GUEST', 20);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (371, 72, 'YELLOW', 'HOME', 10);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (372, 53, 'YELLOW', 'GUEST', 20);

INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (199, 370);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (201, 371);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (201, 372);




