--   0Io92rcH

INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(12, 'Севилья', 'LA');



INSERT INTO PUBLIC.FOOTBALL_BOOKIE_STATS
(ID, DRAW_RATE, GUEST_RATE, HOME_RATE)
VALUES(77, 7, 10, 1.22);

INSERT INTO PUBLIC.FOOTBALL_REFEREE
(ID, NAME)
VALUES(10, 'Гонсалес Г. (Исп)');


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(223, 0, 1, 'FIRST', 1, 'HOME', 1, 7, 2, 1, 1, 42, 2, 6, 12, 4, 1, 58);

INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(225, 1, 1, 'SECOND', 2, 'DRAW', 2, 5, 6, 2, 4, 54, 1, 4, 6, 2, 1, 46);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(224, 1, 2, 'MATCH', 3, 'HOME', 3, 12, 8, 3, 5, 48, 3, 10, 18, 6, 2, 52);


INSERT INTO PUBLIC.FOOTBALL_MATCH_INFO
(ID, FIRST_PERIOD_ID, MATCH_ID, SECOND_PERIOD_ID)
VALUES(77, 223, 224, 225);


INSERT INTO PUBLIC.FOOTBALL_MATCH
(ID, CHAMPIONSHIP, "DATE", MYSCORE_CODE, SEASON, BOOKIE_STATS_ID, GUEST_TEAM_ID, HOME_TEAM_ID, MATCH_INFO_ID, REFEREE_ID)
VALUES(77, 'LA', '2017-11-04 22:45:00.000', '0Io92rcH', 'S2017', 77, 12, 20, 77, 10);


INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (409, 94, 'YELLOW', 'HOME', 20);

INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (225, 409);




