--   fFudm6h6
INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(7, 'Депортиво', 'LA');



INSERT INTO PUBLIC.FOOTBALL_BOOKIE_STATS
(ID, DRAW_RATE, GUEST_RATE, HOME_RATE)
VALUES(24, 11, 21, 1.1);


INSERT INTO PUBLIC.FOOTBALL_REFEREE
(ID, NAME)
VALUES(23, 'Лахос А. (Исп)');



INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(64, 0, 2, 'FIRST', 2, 'HOME', 1, 5, 3, 2, 1, 35, 5, 5, 13, 8, 2, 65);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(66, 0, 2, 'SECOND', 2, 'HOME', 2, 5, 7, 1, 2, 43, 1, 7, 10, 3, 0, 57);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(65, 0, 4, 'MATCH', 4, 'HOME', 3, 10, 10, 3, 3, 39, 6, 12, 23, 11, 2, 61);


INSERT INTO PUBLIC.FOOTBALL_MATCH_INFO
(ID, FIRST_PERIOD_ID, MATCH_ID, SECOND_PERIOD_ID)
VALUES(24, 64, 65, 66);


INSERT INTO PUBLIC.FOOTBALL_MATCH
(ID, CHAMPIONSHIP, "DATE", MYSCORE_CODE, SEASON, BOOKIE_STATS_ID, GUEST_TEAM_ID, HOME_TEAM_ID, MATCH_INFO_ID, REFEREE_ID)
VALUES(24, 'LA', '2017-12-17 22:45:00.000', 'fFudm6h6', 'S2017', 24, 7, 8, 24, 23);

INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (128, 32, 'YELLOW', 'GUEST', 7);

INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS
(FOOTBALL_PERIOD_ID, CARDS_ID)
VALUES(64, 128);


