--   tU6FzT80
INSERT INTO PUBLIC.FOOTBALL_TEAM
(ID, NAME, CHAMPIONSHIP)
VALUES(6, 'Вильярреал', 'LA');



INSERT INTO PUBLIC.FOOTBALL_BOOKIE_STATS
(ID, DRAW_RATE, GUEST_RATE, HOME_RATE)
VALUES(33, 4.33, 1.57, 5.5);


INSERT INTO PUBLIC.FOOTBALL_REFEREE
(ID, NAME)
VALUES(21, 'Bengoetxea R. (Исп)');


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(91, 0, 0, 'FIRST', 0, 'DRAW', 3, 7, 5, 1, 2, 70, 1, 9, 6, 3, 2, 30);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(93, 2, 0, 'SECOND', 2, 'GUEST', 1, 6, 11, 5, 3, 66, 1, 9, 3, 2, 1, 34);


INSERT INTO PUBLIC.FOOTBALL_PERIOD
(ID, GUEST_SCORE, HOME_SCORE, PERIOD_STATUS, TOTAL_SCORE, WINNER, GUEST_CORNERS, GUEST_FOULS, GUEST_HITS, GUEST_HITS_ON_TARGET, GUEST_OFFSIDES, GUEST_POSSESSION, HOME_CORNERS, HOME_FOULS, HOME_HITS, HOME_HITS_ON_TARGET, HOME_OFFSIDES, HOME_POSSESSION)
VALUES(92, 2, 0, 'MATCH', 2, 'GUEST', 4, 13, 16, 6, 5, 68, 2, 18, 9, 5, 3, 32);


INSERT INTO PUBLIC.FOOTBALL_MATCH_INFO
(ID, FIRST_PERIOD_ID, MATCH_ID, SECOND_PERIOD_ID)
VALUES(33, 91, 92, 93);


INSERT INTO PUBLIC.FOOTBALL_MATCH
(ID, CHAMPIONSHIP, "DATE", MYSCORE_CODE, SEASON, BOOKIE_STATS_ID, GUEST_TEAM_ID, HOME_TEAM_ID, MATCH_INFO_ID, REFEREE_ID)
VALUES(33, 'LA', '2017-12-10 22:45:00.000', 'tU6FzT80', 'S2017', 33, 8, 6, 33, 21);

INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (171, 45, 'YELLOW', 'GUEST', 8);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (172, 60, 'RED', 'HOME', 6);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (173, 61, 'YELLOW', 'HOME', 6);
INSERT INTO PUBLIC.FOOTBALL_CARD (ID, MINUTE, TYPE, WHO, TEAM_ID) VALUES (174, 86, 'YELLOW', 'HOME', 6);

INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (91, 171);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (93, 172);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (93, 173);
INSERT INTO PUBLIC.FOOTBALL_PERIOD_CARDS (FOOTBALL_PERIOD_ID, CARDS_ID) VALUES (93, 174);


