SELECT hp.HOME_MINOR_PENALTIES_AMOUNT, hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.FIRST_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT, hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.SECOND_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT , hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.THIRD_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT , hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.MATCH_ID AND MYSCORE_CODE='AqombNzc'