SELECT hp.HOME_MINOR_PENALTIES_AMOUNT, hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.FIRST_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT, hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.SECOND_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT , hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.THIRD_PERIOD_ID AND MYSCORE_CODE='AqombNzc'
UNION ALL
SELECT hp.HOME_MINOR_PENALTIES_AMOUNT , hp.GUEST_MINOR_PENALTIES_AMOUNT FROM HOCKEY_PERIOD hp, HOCKEY_MATCH_INFO hmi, HOCKEY_MATCH hm  WHERE  hm.MATCH_INFO_ID=hmi.ID
AND hp.ID=hmi.MATCH_ID AND MYSCORE_CODE='AqombNzc'


DROP TABLE PUBLIC.FOOTBALL_FUTURE_MATCH_INFO ;
DROP TABLE PUBLIC.FOOTBALL_FUTURE_MATCH_SQUAD_INFO ;
DROP TABLE PUBLIC.FOOTBALL_FUTURE_MATCH_SQUAD_INFO_LINE_UPS ;
DROP TABLE PUBLIC.FOOTBALL_FUTURE_MATCH_SQUAD_INFO_SUBSTITUTIONS ;
DROP TABLE PUBLIC.FOOTBALL_SQUAD_PLAYER ;
DROP TABLE PUBLIC.FOOTBALL_SQUAD_PLAYER_SEASON_STATS ;
DROP TABLE PUBLIC.FOOTBALL_TEAM_SQUAD ;
DROP TABLE PUBLIC.FOOTBALL_TEAM_SQUAD_SQUAD_PLAYERS ;



SELECT fc.* FROM FOOTBALL_CARD fc, FOOTBALL_MATCH fm, FOOTBALL_MATCH_INFO fmi  , FOOTBALL_PERIOD_CARDS fpc
WHERE fm.MYSCORE_CODE='AoGZZeIk' AND fm.MATCH_INFO_ID=fmi.ID AND (fmi.FIRST_PERIOD_ID=fpc.FOOTBALL_PERIOD_ID OR fmi.SECOND_PERIOD_ID=fpc.FOOTBALL_PERIOD_ID) AND fc.ID=fpc.CARDS_ID

SELECT fpc.* FROM FOOTBALL_MATCH fm, FOOTBALL_MATCH_INFO fmi  , FOOTBALL_PERIOD_CARDS fpc
WHERE fm.MYSCORE_CODE='lbS7cBXA' AND fm.MATCH_INFO_ID=fmi.ID AND (fmi.FIRST_PERIOD_ID=fpc.FOOTBALL_PERIOD_ID OR fmi.SECOND_PERIOD_ID=fpc.FOOTBALL_PERIOD_ID)