CREATE TABLE TEAM
(
    ID BIGINT PRIMARY KEY NOT NULL,
    CHAMPIONSHIP VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE CARD
(
    ID BIGINT PRIMARY KEY NOT NULL,
    MINUTE INTEGER NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    WHO VARCHAR(255) NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    CONSTRAINT FK7G6LUMB7J0UJJ9V3S04A7L6SN FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);


CREATE TABLE GOAL
(
    ID BIGINT PRIMARY KEY NOT NULL,
    MINUTE INTEGER NOT NULL,
    WHO_SCORED VARCHAR(255) NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    CONSTRAINT FK5H3N8A7X2JFHRCQOM6C3XTDUF FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);

CREATE TABLE PERIOD
(
    ID BIGINT PRIMARY KEY NOT NULL,
    GUEST_CORNERS INTEGER NOT NULL,
    GUEST_FOULS INTEGER NOT NULL,
    GUEST_HITS INTEGER NOT NULL,
    GUEST_OFFSIDES INTEGER NOT NULL,
    GUEST_POSSESSION INTEGER NOT NULL,
    GUEST_SCORE INTEGER NOT NULL,
    HOME_CORNERS INTEGER NOT NULL,
    HOME_FOULS INTEGER NOT NULL,
    HOME_HITS INTEGER NOT NULL,
    HOME_OFFSIDES INTEGER NOT NULL,
    HOME_POSSESSION INTEGER NOT NULL,
    HOME_SCORE INTEGER NOT NULL,
    PERIOD_STATUS VARCHAR(255) NOT NULL,
    TOTAL_SCORE INTEGER NOT NULL,
    WINNER VARCHAR(255) NOT NULL
);

CREATE TABLE PERIOD_CARDS
(
    PERIOD_ID BIGINT NOT NULL,
    CARDS_ID BIGINT NOT NULL,
    CONSTRAINT CONSTRAINT_D PRIMARY KEY (PERIOD_ID, CARDS_ID),
    CONSTRAINT FKNG3DBGWYPWPGONFD3TWNM54IM FOREIGN KEY (PERIOD_ID) REFERENCES PERIOD (ID),
    CONSTRAINT FK4DI3HW7WAINVNUCW3QYOPFTLD FOREIGN KEY (CARDS_ID) REFERENCES CARD (ID)
);

CREATE TABLE PERIOD_GOALS
(
    PERIOD_ID BIGINT NOT NULL,
    GOALS_ID BIGINT NOT NULL,
    CONSTRAINT CONSTRAINT_D2 PRIMARY KEY (PERIOD_ID, GOALS_ID),
    CONSTRAINT FKMTLHNFQA5JHHPE3XP0BY4YMT7 FOREIGN KEY (PERIOD_ID) REFERENCES PERIOD (ID),
    CONSTRAINT FK4SQ2O5V32J0GEGT7LW6JAK47S FOREIGN KEY (GOALS_ID) REFERENCES GOAL (ID)
);

CREATE TABLE MATCH_INFO
(
    ID BIGINT PRIMARY KEY NOT NULL,
    FIRST_PERIOD_ID BIGINT NOT NULL,
    SECOND_PERIOD_ID BIGINT NOT NULL,
    CONSTRAINT FKO6A89UMOTHFH5PGJFM9A4R02S FOREIGN KEY (FIRST_PERIOD_ID) REFERENCES PERIOD (ID),
    CONSTRAINT FK1B3PVWJBUX64U1RMGOD4QLFJ8 FOREIGN KEY (SECOND_PERIOD_ID) REFERENCES PERIOD (ID)
);

CREATE TABLE MATCH
(
    ID BIGINT PRIMARY KEY NOT NULL,
    CHAMPIONSHIP VARCHAR(255) NOT NULL,
    DATE TIMESTAMP NOT NULL,
    MYSCORE_CODE VARCHAR(8) NOT NULL,
    SEASON VARCHAR(255) NOT NULL,
    GUEST_TEAM_ID BIGINT NOT NULL,
    HOME_TEAM_ID BIGINT NOT NULL,
    MATCH_INFO_ID BIGINT NOT NULL,
    CONSTRAINT FKKKHVBVELAJJHOX9D9CECMBB1R FOREIGN KEY (GUEST_TEAM_ID) REFERENCES TEAM (ID),
    CONSTRAINT FK6IHEFB9R7F0FCM0XUVES72B2L FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAM (ID),
    CONSTRAINT FKNVYC28KAO7M3XHY7FE88SOTW9 FOREIGN KEY (MATCH_INFO_ID) REFERENCES MATCH_INFO (ID)
);

