package com.savik;


public enum ContainerType {
    ROOT,
    GENERAL,
    HOME,
    GUEST,
    TOTAL,
    OTHER,
    EVEN,
    FIRST_GOAL_BEFORE,
    LAST_GOAL_AFTER,
    TOTAL_OVER,
    TOTAL_OVER_ALL_PERIODS,
    TOTAL_UNDER_ALL_PERIODS,
    TOTAL_UNDER,
    BOTH_TEAMS_TOTAL_UNDER,
    BOTH_TEAMS_TOTAL_OVER,
    WIN_AND_TOTAL_OVER,
    WIN_AND_TOTAL_UNDER,
}
