logging:
  level:
    org:
      hibernate: trace


spring:
    datasource:
        url: jdbc:h2:file:~/stats;AUTO_SERVER=TRUE;FILE_LOCK=SOCKET
        driver-class-name: org.h2.Driver
        user: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create