logging:
  level:
    org:
      hibernate: error

server:
    port: 9999

spring:
    datasource:
        url: jdbc:h2:file:./stats;AUTO_SERVER=TRUE;FILE_LOCK=SOCKET
        driver-class-name: org.h2.Driver
        user: sa
        password:
    jpa:
        properties:
              hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: true
        show-sql: false