logging:
  level:
    org:
      hibernate: trace


spring:
    datasource:
        url: jdbc:h2:file:~/stats;AUTO_SERVER=TRUE;FILE_LOCK=SOCKET
        driver-class-name: org.h2.Driver
        user: sa
        password:
    jpa:
        generate-ddl: true
        properties:
              hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create