fsign: SW9D1eZo
url:
  generalinfo: http://d.myscore.ru/x/feed/d_su_%s_ru_1
  statsinfo: http://d.myscore.ru/x/feed/d_st_%s_ru_1
  summary: http://www.myscore.ru/match/%s/#match-summary
  odds: http://d.myscore.com.ua/x/feed/d_od_%s_ru_1_eu
