fsign: SW9D1eZo
url:
  generalinfo: http://d.myscore.ru/x/feed/d_su_%s_ru_1
  statsinfo: http://d.myscore.ru/x/feed/d_st_%s_ru_1
  summary: http://www.myscore.ru/match/%s/#match-summary
  odds: http://d.myscore.com.ua/x/feed/d_od_%s_ru_1_eu
  snookerOdds: http://d.myscore.com.ua/x/feed/df_dos_1_%s_
  footballMatches: http://d.myscore.com.ua/x/feed/f_1_%s_3_ru_1
  hockeyMatches: http://d.myscore.com.ua/x/feed/f_4_%s_3_ru_1
  teamInfo: https://www.myscore.com.ua/%s
  matchSquad: https://d.myscore.com.ua/x/feed/d_li_%s_ru_1
